modLoader = "javafml"
loaderVersion = "[1,)"
license="MIT"

issueTrackerURL="https://github.com/OffsetMods538/MonkeyLib538/issues"


[[mixins]]
config="monkeylib538.modded.mixins.json"


[[mods]]
modId="monkeylib538"
displayName="MonkeyLib538"
version="${modVersion}"
displayURL="https://modrinth.com/mod/monkeylib538"
authors="OffsetMonkey538"
description="A library mod for OffsetMonkey538s mods"


[[dependencies.monkeylib538]]
modId="minecraft"
type="required"
versionRange="${neoforgeSupportedMinecraftVersions}"
ordering="NONE"
side="BOTH"
