modLoader = "javafml"
loaderVersion = "[1,)"
license="MIT"

issueTrackerURL="https://github.com/OffsetMods538/MonkeyLib538/issues"


[[mods]]
modId="monkeylib538_common"
displayName="MonkeyLib538 Common"
version="${modVersion}"
displayURL="https://modrinth.com/mod/monkeylib538"
authors="OffsetMonkey538"
description="A library mod for OffsetMonkey538s mods"
